DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS admins;

CREATE TABLE scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date INTEGER NOT NULL,
    score INTEGER NOT NULL
);

CREATE TABLE admins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);